### ISSUE TITLE
Support ARM64 Homebrew

### ISSUE THREAD

**Issue by kendfinger** [mbullington/goodpkg#1]
Homebrew on Apple Silicon lives at `/opt/homebrew` by default. The sandbox disallows loading of dynamic libraries linked into the node binary since they are in /opt/homebrew

It may also be worth it to run brew --prefix to get the prefix ahead of time on macOS to avoid locking into /usr/local and /opt/homebrew. Homebrew could in theory be installed to any prefix, though that is not an officially supported install method.

```bash
kendfinger@titanium boot-os % goodpkg npm
⚠️ ⚠️ ⚠️  It's very important you see this!
⚠️ ⚠️ ⚠️  Otherwise you're not using goodpkg
/var/folders/62/3jrzv6w16bjbcdtvw17cgsxh0000gn/T/goodpkg-wEZksZ/sandbox.sb
dyld[74779]: Library not loaded: /opt/homebrew/opt/libuv/lib/libuv.1.dylib
  Referenced from: /opt/homebrew/Cellar/node/17.0.1/bin/node
  Reason: tried: '/opt/homebrew/opt/libuv/lib/libuv.1.dylib' (file system sandbox blocked open()), '/usr/local/lib/libuv.1.dylib' (no such file), '/usr/lib/libuv.1.dylib' (no such file)
```

**Comment by mbullington** [comment]
Hey thanks!!

**Comment by mbullington** [comment]
I had a passing knowledge that `/opt/homebrew` was the new location for M1 but totally forgot. Hopefully works now.
